### ISSUE TITLE
［機能追加要望］コドン位置ごとにアライメントを分割する

### ISSUE THREAD

**Issue by HS6986** [kfuku52/cdskit#6]
国立遺伝学研究所 新分野創造センター
准教授 福島健児先生

こちらの便利なツールを開発していただき誠にありがとうございます．

最近発表されたトリミングツールであるPhyIN（[Maddison, 2024](https://doi.org/10.7717/peerj.18504)）を分子系統解析に使用したいと考えています．しかし，タンパク質コード領域の配列にPhyINを直接適用すると，コドン位置ごとに進化速度が異なる（特に第3コドン位置の進化速度が速く飽和しやすい）ことから，飽和があまり起きていないコドン位置のphylogenetic signalがあまり矛盾していないブロックでも，飽和が多く起きているコドン位置の影響によりトリミングされてしまう可能性が高いと考えています．

この問題を避けるためには，アライメントをコドン位置ごとに別々にトリミングするのが賢明だと考えていて，それをするには，PhyINの機能を拡張させたりしない限りは（[MIT licenseなので](https://github.com/wmaddisn/PhyIN)自由に拡張，配布できます）アライメントをコドン位置ごとに分割することが必要なのですが，私の知る限りそのような機能を実装したツールはないようです（ブラウザ上で動作するツールがいくつか[（例）](https://www.bioinformatics.org/sms2/split_codons.html)見つかるのですが思ったようには動かず，アライメントビューアの[AliView](https://ormbunkar.se/aliview/)やGitHub上のツール[Nucleotide-Codon-Position-Parser](https://github.com/ndwhelan/Nucleotide-Codon-Position-Parser)でも同じことが出来るはずなのですが，どちらも上手く動きませんでした）．自分で実装することも出来るのですが，cdskitにこの機能を追加していただければ，恐らくPhyINの使用時に限らずユーザーにとって便利な場合があるのではないかと考えご提案させていただきます．

以下のような動作を期待しています（入力，出力ともにFASTAの場合）．

**入力ファイル**
```
>A
ATATAT
>B
TAGGAT
```

**出力ファイル**
（第1コドン位置）
```
>A
AT
>B
TG
```
（第2コドン位置）
```
>A
TA
>B
AA
```
（第3コドン位置）
```
>A
AT
>B
GT
```

ご多忙のところ恐れ入りますが，ご検討いただければ幸いです．

**Comment by kfuku52** [comment]
I've implemented the requested function in `cdskit split`. Feel free to review it here:
https://github.com/kfuku52/cdskit/wiki/cdskit-split

**Comment by HS6986** [comment]
Thank you very much! This function worked well for my dataset.

Could you implement options like `-pre` and `--prefix` in `cdskit split`, as in [IQ-TREE](http://www.iqtree.org/doc/Command-Reference)? The default value could be set to the input file name. For example, if `-pre Gene1` is specified, the output file names would be like `Gene1_1st_codon_positions.fasta`, `Gene1_2nd_codon_positions.fasta`, and `Gene1_3rd_codon_positions.fasta`. These options would be useful for downstream analyses.

I would appreciate it if you could consider adding these options.

**Comment by kfuku52** [comment]
Sure, `--prefix` should work now. https://github.com/kfuku52/cdskit/commit/ee77214ce3484695a63bc29d97367f61d9e873ba

**Comment by HS6986** [comment]
The implemented option worked properly. Thanks again!
